# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 普

email: polarlion@qq.com



description: > # this means to ignore newlines until "baseurl:"
  千山鸟飞绝 万径人踪灭<br />
  孤舟蓑笠翁 独钓寒江雪
# baseurl: "/test" # the subpath of your site, e.g. /blog
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
weibo_username: 普拉狮普拉狮
twitter_username: Polarlion
github_username:  polarlion
github: https://github.com/PolarLion/polarlion.github.io


safe: true
# lsi: false
# pygments: true
simple_search: http://google.com/search

# Build settings
markdown: kramdown
# highlighter: rouge
excerpt_separator: "\n\n"




# port: 5000